import = ["~/dotfiles/alacritty/gruvbox-dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
padding = { x = 6, y = 6 }
dynamic_padding = true
class = { general = "Alacritty", instance = "Alacritty" }

[env]
TERM = "xterm-256color"
